#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import tarfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Tuple


ROOT = Path.cwd()
VERSION = "12.10.53"

READY_52A = ROOT / "release/final_readiness/FINAL_RELEASE_READINESS_MANIFEST_V12_10_52A.json"

OUT_DIR = ROOT / "release/v12_10_53"
DIST_DIR = ROOT / "dist"

SUMMARY_MD = OUT_DIR / "RELEASE_SUMMARY_V12_10_53.md"
CHANGELOG_MD = OUT_DIR / "CHANGELOG_V12_10_22_TO_V12_10_52A.md"
ARTIFACT_MANIFEST_JSON = OUT_DIR / "RELEASE_ARTIFACT_MANIFEST_V12_10_53.json"
TAG_MANIFEST_JSON = OUT_DIR / "TAG_MANIFEST_V12_10_53.json"
REPORT_MD = OUT_DIR / "RELEASE_PACKAGE_REPORT_V12_10_53.md"

TARBALL = DIST_DIR / "SOCMINT-PROJECT-v12.10.53-release.tar.gz"
ZIPFILE = DIST_DIR / "SOCMINT-PROJECT-v12.10.53-release.zip"

EXPECTED_HEAD = "0018_approved_model_migration"
EXPECTED_BRANCH = "feat/v12.10.22-12.10.28-command-center"


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


def run(cmd: List[str]) -> Tuple[int, str]:
    try:
        out = subprocess.check_output(cmd, cwd=ROOT, stderr=subprocess.STDOUT, text=True)
        return 0, out.strip()
    except subprocess.CalledProcessError as exc:
        return exc.returncode, exc.output.strip()


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def file_info(path: Path) -> Dict[str, Any]:
    return {
        "path": str(path),
        "exists": path.exists(),
        "size_bytes": path.stat().st_size if path.exists() else None,
        "sha256": sha256(path) if path.exists() else None,
    }


def load_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise SystemExit(f"Missing required file: {path}")
    return json.loads(path.read_text())


def list_release_files() -> List[Path]:
    patterns = [
        "release/V12_10_*.md",
        "release/final_readiness/*V12_10_52A*",
        "release/baseline_aware_db_smoke/*V12_10_51*",
        "release/downgrade_symmetry_repair/*V12_10_50*",
        "release/full_db_smoke_trace/*V12_10_48*",
        "release/existing_table_collision_guard/*V12_10_49*",
        "release/v12_10_53/*",
        "scripts/*v12_10_*.py",
        "scripts/test_v12_10_*.sh",
        "tests/test_v12_10_*.py",
        "migrations/versions/0018_approved_model_migration.py",
    ]

    files: List[Path] = []
    for pattern in patterns:
        files.extend(ROOT.glob(pattern))

    deduped = []
    seen = set()
    for p in files:
        if p.is_file() and str(p) not in seen:
            seen.add(str(p))
            deduped.append(p)

    return sorted(deduped)


def write_changelog() -> Dict[str, Any]:
    code, out = run(["git", "log", "--oneline", "--decorate", "--no-merges", "--reverse"])
    commits = out.splitlines() if code == 0 and out else []

    # Slice from first relevant v12.10.22 marker if present.
    start_idx = 0
    for idx, line in enumerate(commits):
        if "12.10.22" in line or "v12.10.22" in line:
            start_idx = idx
            break

    sliced = commits[start_idx:]

    lines = [
        "# Changelog — v12.10.22 to v12.10.52A",
        "",
        "Generated by v12.10.53 release package builder.",
        "",
    ]

    if sliced:
        for line in sliced:
            lines.append(f"- `{line}`")
    else:
        lines.append("- No git log entries captured.")

    CHANGELOG_MD.write_text("\n".join(lines))

    return {
        "git_log_returncode": code,
        "commit_count": len(sliced),
        "source_commit_count": len(commits),
        "changelog_path": str(CHANGELOG_MD),
    }


def write_summary(context: Dict[str, Any]) -> None:
    lines = [
        "# SOCMINT-PROJECT v12.10.53 Release Summary",
        "",
        f"- **release_status**: `{context['release_status']}`",
        f"- **source_readiness**: `{READY_52A}`",
        f"- **branch**: `{context['branch']}`",
        f"- **commit**: `{context['commit']}`",
        f"- **alembic_head**: `{context['alembic_head']}`",
        f"- **schema_lock**: `{context['schema_lock']}`",
        "- **production_db_touched**: `False`",
        "- **real_config_upgrade_run**: `False`",
        "",
        "## Canonical gate",
        "",
        "- v12.10.51 baseline-aware DB smoke: `PASS GO`",
        "- v12.10.52A final readiness: `PASS GO`",
        "- Alembic head: `0018_approved_model_migration`",
        "",
        "## Package artifacts",
        "",
        f"- `{TARBALL}`",
        f"- `{ZIPFILE}`",
        "",
        "## Notes",
        "",
        "This release package is a local artifact bundle only. It does not run Alembic upgrade against any real configured database.",
    ]

    SUMMARY_MD.write_text("\n".join(lines))


def create_archives(files: List[Path]) -> Dict[str, Any]:
    DIST_DIR.mkdir(parents=True, exist_ok=True)

    if TARBALL.exists():
        TARBALL.unlink()
    if ZIPFILE.exists():
        ZIPFILE.unlink()

    with tarfile.open(TARBALL, "w:gz") as tar:
        for p in files:
            tar.add(p, arcname=str(p.relative_to(ROOT)))

    with zipfile.ZipFile(ZIPFILE, "w", compression=zipfile.ZIP_DEFLATED) as z:
        for p in files:
            z.write(p, arcname=str(p.relative_to(ROOT)))

    return {
        "tarball": file_info(TARBALL),
        "zip": file_info(ZIPFILE),
    }


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    DIST_DIR.mkdir(parents=True, exist_ok=True)

    readiness = load_json(READY_52A)

    branch_code, branch = run(["git", "branch", "--show-current"])
    commit_code, commit = run(["git", "rev-parse", "--short", "HEAD"])
    full_commit_code, full_commit = run(["git", "rev-parse", "HEAD"])
    status_code, git_status = run(["git", "status", "--short"])
    heads_code, heads_out = run(["alembic", "heads"])

    errors: List[str] = []
    warnings: List[str] = []

    if readiness.get("release_status") != "PASS GO":
        errors.append(f"v12.10.52A release_status is not PASS GO: {readiness.get('release_status')}")

    if readiness.get("schema_lock") != "BASELINE_AWARE_DB_SMOKE_GO":
        errors.append(f"schema_lock not GO: {readiness.get('schema_lock')}")

    if readiness.get("production_db_touched") is not False:
        errors.append("v12.10.52A did not prove production_db_touched=false")

    if readiness.get("real_config_upgrade_run") is not False:
        errors.append("v12.10.52A did not prove real_config_upgrade_run=false")

    if heads_code != 0 or EXPECTED_HEAD not in heads_out:
        errors.append(f"Alembic head mismatch: {heads_out}")

    if branch_code != 0 or branch != EXPECTED_BRANCH:
        warnings.append(f"Unexpected branch: {branch}; expected {EXPECTED_BRANCH}")

    if status_code == 0 and git_status:
        warnings.append("Working tree has uncommitted changes; release package includes current files but tag should wait for clean tree.")

    context = {
        "release_status": "PASS GO" if not errors else "HOLD",
        "branch": branch,
        "commit": commit,
        "full_commit": full_commit,
        "alembic_head": EXPECTED_HEAD if EXPECTED_HEAD in heads_out else heads_out,
        "schema_lock": readiness.get("schema_lock"),
    }

    write_summary(context)
    changelog = write_changelog()

    files = list_release_files()

    # Ensure summary/changelog/manifests are included.
    files.extend([SUMMARY_MD, CHANGELOG_MD])
    files = sorted({p for p in files if p.exists() and p.is_file()})

    archive_info = create_archives(files)

    artifact_manifest = {
        "version": VERSION,
        "generated_at": now(),
        "release_status": context["release_status"],
        "branch": branch,
        "commit": commit,
        "full_commit": full_commit,
        "alembic_head": context["alembic_head"],
        "schema_lock": context["schema_lock"],
        "production_db_touched": False,
        "real_config_upgrade_run": False,
        "source_readiness_manifest": str(READY_52A),
        "release_summary": str(SUMMARY_MD),
        "changelog": str(CHANGELOG_MD),
        "artifact_count": len(files),
        "artifacts": [file_info(p) for p in files],
        "archives": archive_info,
        "errors": errors,
        "warnings": warnings,
    }

    ARTIFACT_MANIFEST_JSON.write_text(json.dumps(artifact_manifest, indent=2, sort_keys=True))

    tag_manifest = {
        "version": VERSION,
        "generated_at": now(),
        "recommended_tag": "v12.10.53",
        "tag_message": "SOCMINT-PROJECT v12.10.53 release package",
        "release_status": context["release_status"],
        "branch": branch,
        "commit": full_commit,
        "alembic_head": context["alembic_head"],
        "schema_lock": context["schema_lock"],
        "tarball_sha256": archive_info["tarball"]["sha256"],
        "zip_sha256": archive_info["zip"]["sha256"],
        "create_tag_command": "git tag -a v12.10.53 -m 'SOCMINT-PROJECT v12.10.53 release package'",
        "push_tag_command": "git push origin v12.10.53",
        "safety_note": "Tag only after reviewing manifest and confirming working tree state.",
    }

    TAG_MANIFEST_JSON.write_text(json.dumps(tag_manifest, indent=2, sort_keys=True))
    write_report(artifact_manifest, tag_manifest)

    print(json.dumps({
        "version": VERSION,
        "release_status": context["release_status"],
        "branch": branch,
        "commit": commit,
        "alembic_head": context["alembic_head"],
        "schema_lock": context["schema_lock"],
        "artifact_count": len(files),
        "tarball": str(TARBALL),
        "tarball_sha256": archive_info["tarball"]["sha256"],
        "zip": str(ZIPFILE),
        "zip_sha256": archive_info["zip"]["sha256"],
        "manifest": str(ARTIFACT_MANIFEST_JSON),
        "tag_manifest": str(TAG_MANIFEST_JSON),
        "report": str(REPORT_MD),
        "error_count": len(errors),
        "warning_count": len(warnings),
        "production_db_touched": False,
        "real_config_upgrade_run": False,
    }, indent=2, sort_keys=True))

    return 0 if not errors else 1


def write_report(artifact_manifest: Dict[str, Any], tag_manifest: Dict[str, Any]) -> None:
    lines = [
        "# v12.10.53 Release Package Report",
        "",
        f"- **release_status**: `{artifact_manifest['release_status']}`",
        f"- **branch**: `{artifact_manifest['branch']}`",
        f"- **commit**: `{artifact_manifest['commit']}`",
        f"- **alembic_head**: `{artifact_manifest['alembic_head']}`",
        f"- **schema_lock**: `{artifact_manifest['schema_lock']}`",
        "- **production_db_touched**: `False`",
        "- **real_config_upgrade_run**: `False`",
        f"- **artifact_count**: `{artifact_manifest['artifact_count']}`",
        "",
        "## Archives",
        "",
        f"- tarball: `{artifact_manifest['archives']['tarball']['path']}`",
        f"- tarball_sha256: `{artifact_manifest['archives']['tarball']['sha256']}`",
        f"- zip: `{artifact_manifest['archives']['zip']['path']}`",
        f"- zip_sha256: `{artifact_manifest['archives']['zip']['sha256']}`",
        "",
        "## Tag",
        "",
        f"- recommended_tag: `{tag_manifest['recommended_tag']}`",
        f"- create: `{tag_manifest['create_tag_command']}`",
        f"- push: `{tag_manifest['push_tag_command']}`",
        "",
        "## Errors",
        "",
    ]

    if artifact_manifest["errors"]:
        for err in artifact_manifest["errors"]:
            lines.append(f"- {err}")
    else:
        lines.append("- none")

    lines.extend(["", "## Warnings", ""])

    if artifact_manifest["warnings"]:
        for warning in artifact_manifest["warnings"]:
            lines.append(f"- {warning}")
    else:
        lines.append("- none")

    REPORT_MD.write_text("\n".join(lines))


if __name__ == "__main__":
    raise SystemExit(main())
