from .dashboard import create_app
from .full_report_alias import register_full_report_aliases
from .full_report_browser import register_full_report_browser_flow
from .full_report_history import register_full_report_history_routes
from .full_report_retention import register_full_report_retention_routes
from .command_center_routes import register_command_center_routes
from .connector_runtime_routes import register_connector_runtime_routes


app = create_app()
register_full_report_aliases(app)
register_full_report_browser_flow(app)
register_full_report_history_routes(app)
register_full_report_retention_routes(app)
register_command_center_routes(app)
register_connector_runtime_routes(app)
