from .dashboard import create_app
from .full_report_alias import register_full_report_aliases
from .full_report_browser import register_full_report_browser_flow
from .full_report_history import register_full_report_history_routes
from .full_report_retention import register_full_report_retention_routes
from .command_center_routes import register_command_center_routes
from .connector_runtime_routes import register_connector_runtime_routes
from .spine_intelligence_routes import register_spine_intelligence_routes
from .ultimate_dossier_routes import register_ultimate_dossier_routes
from .membership_routes import register_membership_routes
from .billing_routes import register_billing_routes
from .tor_routes import register_tor_routes
from .analyst_ux_routes import register_analyst_ux_routes
from .export_quality_routes import register_export_quality_routes
from .connector_sdk_routes import register_connector_sdk_routes
from .production_release_routes import register_production_release_routes
from .certification_dashboard_routes import register_certification_dashboard_routes
from .distribution_action_routes import register_distribution_action_routes
from .distribution_packet_export_routes import register_distribution_packet_export_routes
from .distribution_export_verification_routes import register_distribution_export_verification_routes
from .distribution_release_ledger_routes import register_distribution_release_ledger_routes
from .release_ledger_dashboard_routes import register_release_ledger_dashboard_routes

app = create_app()
register_full_report_aliases(app)
register_full_report_browser_flow(app)
register_full_report_history_routes(app)
register_full_report_retention_routes(app)
register_command_center_routes(app)
register_connector_runtime_routes(app)
register_spine_intelligence_routes(app)
register_ultimate_dossier_routes(app)
register_membership_routes(app)
register_billing_routes(app)
register_tor_routes(app)
register_analyst_ux_routes(app)
register_export_quality_routes(app)
register_connector_sdk_routes(app)
register_production_release_routes(app)
register_certification_dashboard_routes(app)
register_distribution_action_routes(app)
register_distribution_packet_export_routes(app)
register_distribution_export_verification_routes(app)
register_distribution_release_ledger_routes(app)
register_release_ledger_dashboard_routes(app)
